### ISSUE TITLE
CommandLine Error: Option 'opt-bisect-limit' registered more than once!

### ISSUE THREAD

**Issue by bsauce** [secure-software-engineering/phasar#171]
I have the same problem with <https://github.com/secure-software-engineering/phasar/issues/130>. 

```
john@ubuntu:~/Desktop/phasar/phasar$ phasar-llvm --module test/build_systems_tests/installation_tests/module.ll -D ifds-solvertest
: CommandLine Error: Option 'opt-bisect-limit' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

I use ./bootstrap.sh to install phasar. That's strange. And my environment is Ubuntu 18.04.

I think it is because ./bootstrap.sh install the newest clang-10.0.0. But some code in phasar use the old version of clang/llvm.

**Comment by pdschubert** [comment]
Hello there,

This issue can be fixed by dynamically linking against LLVM/Clang. If I recall correctly, this is also the recommended way with respect to LLVM. You may wish to remove older LLVM/Clang installations on your system or may wish to make sure otherwise that Phasar links to the correct libraries.
