### ISSUE TITLE
Model in IFDSLinearConstantAnalysis

### ISSUE THREAD

**Issue by wcphkust** [secure-software-engineering/phasar#202]
## Idea for the project
The linear constant analysis based on IFDS framework seems incorrect

## Details
It is found that `IFDSLinearConstantAnalysis.h` is defined in the directory of `PhasarLLVM/DataFlowSover/ifdside/Problems`. 
However, according to the [paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.61.8958&rep=rep1&type=pdf), linear constant propagation can not be formulated into an IFDS problem. 
In the implementation, all the flow functions are instantiated as identity function, which is not consistent with the concrete semantics. I wonder whether these configurations are valid or not. The configurations in `IDELinearConstantAnalysis` seem to make sense.

**Comment by pdschubert** [comment]
Hi,

Thanks for your comment. Yeah, I just checked the `IFDSLinearConstantAnalysis` does not have a correct implementation, yet---all flow functions are currently defaulted to identity. Some of the data-flow analyses implemented in Phasar are just small show-case analyses. Writing an actual analysis that is able to correctly analyze real-world code can take a substantial amount of time. Unfortunately, our research group has only a limited amount of time to work on analyses that are not relevant for actual state-of-the-art research. This is one of the reasons we open sourced the framework: anyone can help and implement their own useful analyses that can be shared with the program analysis community.

That being said, a linear constant analysis can also be implemented within IFDS. You can use pairs of variables and their constant value as data-flow domain, for instance. However, that would lead to a very inefficient analysis due to the underlying solver algorithm. So you would rather model it using IDE like in the `IDELinearConstantAnalysis` implementation. My original idea was to show that both approaches are theoretically possible but not necessarily advisable.

If you can invest some spare time, you are free to help out with the `IFDSLinearConstantAnalysis`. Otherwise I'll try to find one of our students how can work on that. Although it is not advisable to encode the problem in IFDS it would still be a good exercise to familiarize oneself with LLVM and IFDS.

Cheers,
Philipp

**Comment by wcphkust** [comment]
Thank you for your reply. But I am confused about the form of flow functions if linear-constant propagation is formulated as an IFDS problem. Is it labeled with a lambda function just as the one in the IDE framework? I suppose the bit-vector representation, i.e., kill-gen function, can not encode the effect of the statement `y = a * x + b`.

**Comment by pdschubert** [comment]
In IFDS you do not have the ability to make use of lambda functions to express value computations. Rather you only have one data-flow domain `D`. The data-flow solver will propagate data-flow facts drawn from the domain through the program. In LLVM, for instance, you could define `D = std::pair<const llvm::Alloca *, int>` to propagate the required information through the program.

IFDS and IDE do not use a bit-vector representation. Instead, the construct the so-call exploded-supergraph. IFDS's four flow functions factories return implementations of the `FlowFunction` interface. Those implementations describe the effects of the current instruction under analysis on the data-flow facts that hold right before that very instruction. The `FlowFunction`s `computeTargets()` function is called on each individual data-flow fact that holds right before the instruction under analysis. The function returns a set of data-flow facts which then, together with the input fact, describe what super-graph edges need to be "drawn".

Say you have the following non-linear instruction `x = y + z`: to kill `x` here you would implement `computeTargets` in such a way that it checks if its input is `x` and if so, return the empty set. Does that make sense to you?

**Comment by wcphkust** [comment]
Yes, I got the idea. I supposed that the fact domain `D` is the set of integer variables and each variable has possibly infinite value. However, under the assumption that an integer-type variable has a finite number of values in the real-world machine, it is feasible to define `D` as  `std::pair<const llvm::Alloca *, int>`. One point is that the upper bound of time complexity is quite high because the `|D|` is extremely large and the time complexity is cubic-dependent to `|D|`.

I went back to this [work](https://thewhitespace.de/publications/shb19-phasar.pdf). The example in List 1.1 is illustrative. Your comments are very clear. Thank you for your detailed explanation. By the way, I am curious about the IDE problem. Based on my investigation, it is found that there are only two typical kinds of IDE problems, namely constant propagation and [software product line analysis](https://www.bodden.de/pubs/bmb+13spllift.pdf). We admire the elegant representation of these IFDS and IDE problems. Can you share more IDE problems in the real-world program analysis?

**Comment by pdschubert** [comment]
That's exactly right: IFDS is theoretically possible, but not at all applicable to larger programs as the time complexity goes through the roof.

We are currently working on an interesting paper that uses a very advanced IDE encoding. We plan to publish that work soon and will make the analysis available as open source as part of Phasar.

I guess iIt makes sense to move this discussion to Phasar's Slack channel. If you send me your e-mail address I'll add you to our channel.

Cheers
