### ISSUE TITLE
LLVM 5.0.1 or 5.0.0 installation for macOS 

### ISSUE THREAD

**Issue by tiganov** [secure-software-engineering/phasar#31]
I am using macOS 10.14.4 and I can't seem to find a way to install LLVM `5.0.0/1`. The install script under `utils/` fails. I've tried using the precompiled libraries available [here](http://releases.llvm.org/download.html), but that didn't work for me. I cannot install older versions of XCode that would allow me to install `5.0.0/1` without downgrading my OS.

**Comment by pdschubert** [comment]
How does the error message look like when using the installer script?
Are you able to run `LLVM 8.0.0` on macOS 10.14.4? We are currently moving towards `LLVM 8.0.0`. We will create a separate branch for that in order to evaluate how much stuff we break/need to fix. We plan to finish the transition to 8.0.0 somewhere next week.

**Comment by tiganov** [comment]
Apologies for the late reply.

LLVM 8.0.0 runs on macOS 10.14.4 - it's the version that ships with the latest version of Xcode, I believe. [Here](https://pastebin.com/9Nf2Vfxr) is some terminal output from running the install script. Also, [here](https://github.com/tiganov/swasar/commit/b253fcebda16143f0b361d7d37ce479d5045a8cd) are the changes I had to make for Phasar build on macOS, at least on my system. I am excited to hear that you will be transitioning to 8.0.0.
