### ISSUE TITLE
plugin make file

### ISSUE THREAD

**Issue by meweez** [secure-software-engineering/phasar#351]
Hello,
there was a problem for MakeFile in `/phasar/examples/plugins`.
```
clang++ -std=c++17 -Wall -Wno-return-type-c-linkage -O0 -fPIC -shared  `llvm-config --cppflags` MyIFDSProblem.cxx -o MyIFDSProblem.so
MyIFDSProblem.cxx:3:10: fatal error: 'phasar/DB/ProjectIRDB.h' file not found
#include "phasar/DB/ProjectIRDB.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:17: recipe for target 'ifdsproblem' failed
make: *** [ifdsproblem] Error 1
```

I replace 

```
$(CXX) $(CXX_FLAGS) $(INCLUDE_DIRS) $(LLVM_FLAGS) $(IFDSPluginSrc) -o $(IFDSPlugin)
```
with 

```
$(CXX) $(CXX_FLAGS) -I$(PHASAR_INCLUDE_DIR) $(LLVM_FLAGS) $(IFDSPluginSrc) -o $(IFDSPlugin)
```
to fix this.

**Comment by me22bee** [comment]
Hello again,
I am a beginner here and I’m a little confused about building plugins.
I have built Phasar on my Ubuntu but in the "/usr/local/phasar/lib" folder I don’t have some .so files corresponding to .cpp files those I have in phasar/lib folder.
For example, how can I build `IFDSTaintAnalysis` and use this as a plugin?
How can I build my own plugin?
Can anyone show me the row?
Thanks a lot.

**Comment by MMory** [comment]
Meanwhile, the plugin example is broken more, due to the InitialSeeds refactoring. The Makefile implies phasar to be installed to the system. It should be replaced with a proper CMakeLists.txt.

All of this would be a good first issue for newbies, despite not being the easiest possible "good first issue" - maybe a good second issue ;-)

**Comment by fabianbs96** [comment]
Plugins were removed from phasar
