### ISSUE TITLE
propagating tainted value generated by a callee

### ISSUE THREAD

**Issue by ihavenomoneybuthope** [secure-software-engineering/phasar#52]
First, thank you all for this project. it's a blast. I'm really having fun working on this.
I have the following trivial code: 
```
int doit( ){
	int z, k;
	z = taint();
        k = id(z);
	return k;
}
int id(int i) { return i; }
int main(int argc, char **argv) {
	int o = doit();
	print(o);
	return 0;
}
```
where `taint` is the source and `print` is the sink. It produces the following LLVM IR (has been opt via mem2reg):
```
define dso_local i32 @doit() #0 {
  %1 = call i32 @taint()
  %2 = call i32 @id(i32 %1)
  ret i32 %2
}
define dso_local i32 @id(i32) #0 {
  ret i32 %0
}
define dso_local i32 @main(i32, i8**) #0 {
  %3 = call i32 @doit()
  call void @print(i32 %3)
  ret i32 0
}
```
The goal is to detect the data flow from the `taint` to the `print`. I'm using the json file to specify source and sink functions via `TaintSensitiveFunctions`.

The flowFunctions implementation for `getCallFlowFunction` , `getCallToRetFlowFunction` and `getRetFlowFunction` is attached.  In `getCallFlowFunction` when the sink is called, data facts are Killed. The tainted value is Generated in `getCallToRetFlowFunction`.

The problem is, looks like when the call-site to `print` is being analyzed there is no data fact for the `taint` return value.

Please, what am I doing wrong?

cheers

[flowfunctions.txt](https://github.com/secure-software-engineering/phasar/files/3451861/flowfunctions.txt)

**Comment by ihavenomoneybuthope** [comment]
ps: the same code attached as `flowfunctions.txt` works well for the following source code:

```
int id(int i) { return i; }
int main(int argc, char **argv) {
	int o = taint();
        int z = id(o);
	print(z);
	return 0;
}
```

cheers

**Comment by pdschubert** [comment]
Hi,

Thanks for using Phasar, we hope that Phasar can be helpful to you. Writing data-flow analyses can be quite tricky sometimes. Your idea, however, sounds solid. Unfortunately, we do not have the resources to have a detailed look into the flow functions and to debug them. In general, we find it very useful to have a look at the IFDS/IDE dump to spot the place where a data-flow fact has (not) been generated although it should have been, in order to fix the responsible flow function. You may wish to have a look at our built-in show-case IFDSTaintAnalysis implementation, too.

Cheers

**Comment by ihavenomoneybuthope** [comment]
Thanks, appreciated. 
As reference to whom might find in same situation, I spotted the issue in my code. In `summaryFlowFunction` I was returning the Identify instead of `nullptr`. 
Now it works.
