### ISSUE TITLE
running phasar on pldi examples

### ISSUE THREAD

**Issue by ochipara** [secure-software-engineering/phasar#55]
Hi,

I have been trying to run phasar (v0319) on the examples from pldi18 tutorial (e.g., branch.c.ll or assignment_2.c.ll) . I am using the virtual machine that you provided. I am seeing that phasar does not report any leaks for either example when using the ifds-taint default analysis (I obtain similar results for the other default taint analysis). I am not sure what I am missing.

Thanks!

**Comment by pdschubert** [comment]
Hi,

Thanks for your question! The example code provided for the pldi18 tutorial (/home/phasar/Programs/pldi18_tutorial/analyses/target) are intended to be used for a custom analysis. It has been a hands-on task for the participants of the tutorial to implement the flow functions in MyIFDSProblem.cxx (/home/phasar/Programs/pldi18_tutorial/analyses/plugins/MyIFDSProblem.cxx) to encode a small taint analysis that is able to find leaks as present in branch.c.ll, for instance.

The default (built-in) taint analysis needs parametrization: you need to specify sources and sinks in order to find the leaks you are interested in. Please have a look at the TaintSensitiveFunctions class and how it is used within the framework. We improved on the taint analysis configuration in the newer version of PhASAR; it has been refactored to TaintConfiguration.

Please feel free to approach us with further questions. If you wish to be added to Phasar's slack channel, let me know.

Best
Philipp

**Comment by ochipara** [comment]
Dear Philipp,

That works. I used the new version in git. Yes, please add me to Phasar's slack channel.

— Octav

-----
Associate Professor
Department of Computer Science
University of Iowa
http://cs.uiowa.edu/~ochipara/

On Aug 28, 2019, at 8:13 AM, Philipp Schubert <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Thanks for your question! The example code provided for the pldi18 tutorial (/home/phasar/Programs/pldi18_tutorial/analyses/target) are intended to be used for a custom analysis. It has been a hands-on task for the participants of the tutorial to implement the flow functions in MyIFDSProblem.cxx (/home/phasar/Programs/pldi18_tutorial/analyses/plugins/MyIFDSProblem.cxx) to encode a small taint analysis that is able to find leaks as present in branch.c.ll, for instance.

The default (built-in) taint analysis needs parametrization: you need to specify sources and sinks in order to find the leaks you are interested in. Please have a look at the TaintSensitiveFunctions class and how it is used within the framework. We improved on the taint analysis configuration in the newer version of PhASAR; it has been refactored to TaintConfiguration.

Please feel free to approach us with further questions. If you wish to be added to Phasar's slack channel, let me know.

Best
Philipp
